name: HhOJ Judge

on:
  workflow_dispatch:

jobs:
  judge:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      HHOJ_API_URL: ${{ secrets.HHOJ_API_URL }}
      HHOJ_API_KEY: ${{ secrets.HHOJ_API_KEY }}
    steps:
      - name: Setup
        run: sudo apt-get update && sudo apt-get install -y gcc g++ g++-14 mono-complete default-jdk python3 fpc
      - name: Judge
        run: echo "${{ secrets.JUDGE_SCRIPT_B64 }}" | base64 -d > /tmp/judge.py && python3 /tmp/judge.py
